# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py39"
line-length = 120
exclude=[
    ".git,",
    "__pycache__",
    "build",
    "tools/**",
]
lint.select = [
    "A",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "COM",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FBT",
    "FLY",
    "G",
    "I",
    "ICN",
    "INP",
    "INT",
    "ISC",
    "LOG",
    "NPY",
    "PGH",
    "PIE",
    "PLE",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TID",
    "TRIO",
    "TRY",
    "UP",
    "W",
    "YTT",
]
lint.extend-ignore = [
    # TODO: Fix in future
    "E501",  # Line too long
    "E741",  # Ambiguous variable name
    "FBT002", # Bool arg
    "COM812", # May cause conflicts when used with the formatter
    "ISC001",  # May cause conflicts when used with the formatter
]

[lint.per-file-ignores]
"examples/*.py" = [
    "INP001", # examples is part of an implicit namespace package
    "T201", # We need print in our examples
]
"docs/conf.py" = [
    "INP001", # conf.py is part of an implicit namespace package
]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"
